/// <reference types="vite/client" />
/// <reference types="vitest" />
/// <reference types="@remix-run/node/globals" />

declare module "path-esm" {
  /**
   * Returns an object from a path string - the opposite of format().
   *
   * @param path path to evaluate.
   * @throws {TypeError} if `path` is not a string.
   */
  declare function parse(path: string): ParsedPath;

  /**
   * A parsed path object generated by path.parse() or consumed by path.format().
   */
  interface ParsedPath {
    /**
     * The root of the path such as '/' or 'c:\'
     */
    root: string;
    /**
     * The full directory path such as '/home/user/dir' or 'c:\path\dir'
     */
    dir: string;
    /**
     * The file name including extension (if any) such as 'index.html'
     */
    base: string;
    /**
     * The file extension (if any) such as '.html'
     */
    ext: string;
    /**
     * The file name without extension (if any) such as 'index'
     */
    name: string;
  }
}

declare module "daisyui" {
  // eslint-disable-next-line @typescript-eslint/consistent-type-imports
  declare const plugin: import("tailwindcss/types/config").PluginCreator;
  export default plugin;
}
