name: "🙋 Pull Request"

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  development:
    name: 👷 Development
    uses: remix-austin/remixaustin-com/.github/workflows/development.yml@main
    if: ${{ github.event.action != 'closed' }}
